name: hello-world
on: 
  workflow_dispatch:
jobs:
  HelloWorld:
    name: Hello-world
    runs-on: self-hosted
    steps:
      - name: test
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
